
@BASE_URL = http://localhost:8080/api/
@NAME = Sir-Taskalot
@DESCR = At your service, noble one—what task shall I conquer for you today?

GET {{BASE_URL}}digital_assistants
Content-Type: application/json

###

POST {{BASE_URL}}digital_assistants
Content-Type: application/json

{
    "assistantName": "{{NAME}}",
    "assistantMessage": "{{DESCR}}"
}

###

GET {{BASE_URL}}digital_assistants?assistantName={{NAME}}
Content-Type: application/json


###

GET {{BASE_URL}}digital_assistants/message?assistantName={{NAME}}
Content-Type: application/json


